In [2]:
import pandas as pd

In [3]:
df_inpatient_admissions = pd.read_csv('inpatient_admissions.csv')

In [4]:
df_inpatient_admissions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 623 entries, 0 to 622
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   admission_id    623 non-null    object
 1   patient_id      623 non-null    object
 2   admission_date  623 non-null    object
 3   discharge_date  623 non-null    object
dtypes: object(4)
memory usage: 19.6+ KB

In [5]:
df_inpatient_admissions.head()

  admission_id patient_id admission_date discharge_date
0     ADM00001      P0092     2015-01-07     2015-01-08
1     ADM00002      P0070     2015-01-18     2015-01-19
2     ADM00003      P0127     2015-01-19     2015-01-20
3     ADM00004      P0003     2015-01-23     2015-01-24
4     ADM00005      P0085     2015-01-23     2015-01-24

In [6]:
df_employee_satisfaction_survey=pd.read_csv('employee_satisfaction_survey.csv')

In [7]:
df_employee_satisfaction_survey.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 901 entries, 0 to 900
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Timestamp     901 non-null    object
 1   Email         901 non-null    object
 2   Satisfaction  901 non-null    int64
dtypes: int64(1), object(2)
memory usage: 21.2+ KB

In [8]:
df_employee_satisfaction_survey.head()

             Timestamp                   Email  Satisfaction
0  2019-01-09 11:16:03  jack_torrence@acme.com             5
1  2019-01-14 17:03:20        talagbe@acme.com             5
2  2019-06-30 12:27:22       kennetht@acme.com             4
3  2019-09-09 12:30:08        cybarra@acme.com             2
4  2019-11-01 09:33:33      mia_brown@acme.com             4

In [13]:
#Retornando o maior email - Para criar o VARCHAR no SQL
max(df_employee_satisfaction_survey['Email'].str.len())

28