In [37]:
import pandas as pd

In [3]:
df_inpatient_admissions = pd.read_csv('inpatient_admissions.csv')

In [4]:
df_inpatient_admissions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 623 entries, 0 to 622
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   admission_id    623 non-null    object
 1   patient_id      623 non-null    object
 2   admission_date  623 non-null    object
 3   discharge_date  623 non-null    object
dtypes: object(4)
memory usage: 19.6+ KB

In [5]:
df_inpatient_admissions.head()

  admission_id patient_id admission_date discharge_date
0     ADM00001      P0092     2015-01-07     2015-01-08
1     ADM00002      P0070     2015-01-18     2015-01-19
2     ADM00003      P0127     2015-01-19     2015-01-20
3     ADM00004      P0003     2015-01-23     2015-01-24
4     ADM00005      P0085     2015-01-23     2015-01-24

In [6]:
df_employee_satisfaction_survey=pd.read_csv('employee_satisfaction_survey.csv')

In [7]:
df_employee_satisfaction_survey.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 901 entries, 0 to 900
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Timestamp     901 non-null    object
 1   Email         901 non-null    object
 2   Satisfaction  901 non-null    int64
dtypes: int64(1), object(2)
memory usage: 21.2+ KB

In [8]:
df_employee_satisfaction_survey.head()

             Timestamp                   Email  Satisfaction
0  2019-01-09 11:16:03  jack_torrence@acme.com             5
1  2019-01-14 17:03:20        talagbe@acme.com             5
2  2019-06-30 12:27:22       kennetht@acme.com             4
3  2019-09-09 12:30:08        cybarra@acme.com             2
4  2019-11-01 09:33:33      mia_brown@acme.com             4

In [13]:
#Retornando o maior email - Para criar o VARCHAR no SQL
max(df_employee_satisfaction_survey['Email'].str.len())

28

In [20]:
df_grocery_transactions=pd.read_csv('grocery_transactions.csv')

In [21]:
df_grocery_transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87575 entries, 0 to 87574
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   transaction_id        87575 non-null  int64
 1   transaction_datetime  87575 non-null  object
 2   register              87575 non-null  int64
 3   line_item             87575 non-null  int64
 4   upc                   87575 non-null  int64
 5   product_name          87575 non-null  object
 6   quantity              87575 non-null  int64
 7   unit_price            87575 non-null  float64
dtypes: float64(1), int64(5), object(2)
memory usage: 5.3+ MB

In [22]:
df_grocery_transactions.head()

,transaction_id,transaction_datetime,register,line_item,upc,product_name,quantity,unit_price
0,1,2024-01-01 07:14:33,2,1,40000591512,Eggs,2,4.29
1,1,2024-01-01 07:14:33,2,2,40001330902,Milk,1,3.49
2,2,2024-01-01 07:32:13,8,1,40001626658,Parmesan,1,5.49
3,2,2024-01-01 07:32:13,8,2,40001700597,Pasta,1,1.79
4,2,2024-01-01 07:32:13,8,3,40001774536,Pasta Sauce,1,3.29

In [24]:
max(df_grocery_transactions['product_name'].str.len())

14

In [30]:
df_marathon_data = pd.read_csv('marathon-data.csv')

In [31]:
df_marathon_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37250 entries, 0 to 37249
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     37250 non-null  int64
 1   gender  37250 non-null  object
 2   split   37250 non-null  object
 3   final   37250 non-null  object
dtypes: int64(1), object(3)
memory usage: 1.1+ MB

In [32]:
df_marathon_data.head()

   age gender     split     final
0   33      M  01:05:38  02:08:51
1   32      M  01:06:26  02:09:28
2   31      M  01:06:49  02:10:42
3   38      M  01:06:16  02:13:45
4   31      M  01:06:32  02:13:59

In [34]:
df_hotel_booking = pd.read_csv('hotel_bookings.csv')

In [35]:
df_hotel_booking.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39361 entries, 0 to 39360
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   booking_id     39361 non-null  int64
 1   booking_date   39361 non-null  object
 2   cancel_date    10823 non-null  object
 3   checkin_date   39361 non-null  object
 4   checkout_date  39361 non-null  object
 5   is_canceled    39361 non-null  int64
dtypes: int64(2), object(4)
memory usage: 1.8+ MB

In [36]:
df_hotel_booking.head()

   booking_id booking_date cancel_date checkin_date checkout_date  is_canceled
0           1   2014-03-18         NaN   2016-02-25    2016-03-24            0
1           2   2014-04-18         NaN   2015-10-02    2015-10-11            0
2           3   2014-04-30         NaN   2015-08-03    2015-08-10            0
3           4   2014-04-30         NaN   2015-08-03    2015-08-10            0
4           5   2014-04-30         NaN   2015-08-03    2015-08-10            0

In [38]:
df_property_sales = pd.read_csv('manhattan_property_sales.csv')

In [39]:
df_property_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 141 entries, 0 to 140
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   NEIGHBORHOOD    141 non-null    object
 1   ADDRESS         141 non-null    object
 2   ZIP_CODE        141 non-null    int64
 3   BUILDING_CLASS  141 non-null    object
 4   SQUARE_FEET     141 non-null    int64
 5   SALE_PRICE      141 non-null    int64
dtypes: int64(3), object(3)
memory usage: 6.7+ KB

In [40]:
df_property_sales.head()

,NEIGHBORHOOD,ADDRESS,ZIP_CODE,BUILDING_CLASS,SQUARE_FEET,SALE_PRICE
0,CHELSEA,150 WEST 15TH STREET,10011,A4,8997,14999999
1,CHELSEA,348 WEST 22 STREET,10011,A4,3042,13500000
2,CHELSEA,204 WEST 21ST STREET,10011,A4,3365,7650000
3,CHELSEA,481 WEST 22 STREET,10011,A4,3666,0
4,CHELSEA,344 W 22 STREET,10011,A4,4395,13100000

In [55]:
print(f"Neighborhood: {df_property_sales['NEIGHBORHOOD'].str.len().max()}")
print(f"Address: {df_property_sales['ADDRESS'].str.len().max()}")
print(f"Zip_code: {df_property_sales['ZIP_CODE'].astype(str).str.len().max()}")
print(f"Building_class: {df_property_sales['BUILDING_CLASS'].str.len().max()}")

Neighborhood: 18
Address: 22
Zip_code: 5
Building_class: 2

In [60]:
headers = [header.lower() for header in headers]
headers

['neighborhood',
 'address',
 'zip_code',
 'building_class',
 'square_feet',
 'sale_price']